#!/bin/bash

inputLoop() {
  echo -n "> "
  while read line; do
    # the echo "s" sleep bit open the radios vox squelch?
    echo "ss" | festival --tts
    sleep 1 
    echo $line | festival --tts
    echo -n "> "
  done
}

main() {
  echo "$0"
  echo "Dont forget to setup vox 1 [menu] 4"

  inputLoop
}

main $@
